mBoard/mBoard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', include('posts.urls')),
    url(r'^$', views.boards, name='boards'),
    url(r'^boards/(?P<pk>\d+)$', views.topics, name='topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
]

mBoard/posts/urls.py
from django.conf.urls import url
from . import views
#from django.contrib import admin


urlpatterns = [
    url(r'^$', views.boards, name='Boards'),
    #url(r'^boards/(?P<pk>\d+)/$', views.topics, name='topics'),
    # url(r'^(?P<board_name>[/w]+)', views.topics, name='Topics')
    # url(r)
]

mBoard/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    starter = models.ForeignKey(User, related_name='topics')
    replies = models.IntegerField(default=0)
    # broadcast_id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.subject

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts')
    updated_by = models.ForeignKey(User, null=True, related_name='+')

    def __str__(self):
        return self.message[:50]

    def pub_recent(self):
        return self.created_at >= timezone.now() - datetime.timedelta(days=1)

mBoard/posts/forms.py
from django import forms
from .models import Topic

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(), max_length=4000)

    class Meta:
        model = Topic
        fields = ['subject', 'message']

mBoard/posts/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import Board, Topic, Post
from .forms import NewTopicForm

# Create your views here.

def boards(request):
    boards = Board.objects.all()
    return render(request, 'home.html', {'boards': boards})
    # boards_names = list()
    # for board in boards:
    # boards_names.append(board.name)
    # response_html = '<br>'.join(boards_names)
    # return HttpResponse(response_html)

def topics(request, pk):
    board = get_object_or_404(Board, pk=pk)
    return render(request, 'topics.html', {'board': board})
    # topics = Topic.objects.all()
    # topics_names = list()
    # for topic in topics:
    # topics_names.append(topic.subject)
    # response_html = '<br>'.join(topics_names)
    # try:
        # board = Board.objects.get(pk=pk)
    # except Board.DoesNotExist:
    # raise Http404
    #return HttpResponse(response_html)

def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    #print('am board',board);
    user = User.objects.first()

    if request.method == 'POST':
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = user
            topic.save()

            # subject = request.POST['subject']
            # message = request.POST['message']

            # user = User.objects.first()

            # topic = Topic.objects.create(
            #    subject=subject,
            #    board=board,
            #    starter=user
            # )

            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=user,
            )

        return redirect('topics', pk=pk)
    else:
        form = NewTopicForm()
    # return render(request, 'new_topic.html', {'board': board,'pk':pk})
    return render(request, 'new_topic.html', {'board': board, 'form': form})

def posts(request):
    posts = Post.objects.all()
    posts_names = list()

    for post in posts:
        post_names.append(post.message[:50])

    response_html = '<br>'.join(posts_names)

    return HttpResponse(response_html)

mBoard/posts/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Idea Foundation{% endblock %}</title> <!-- change "IDEA FOUNDATION" to project name -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'boards' %}">Idea Foundation</a>
      </div>
    </nav>

    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

mBoard/posts/templates/home.html
{% extends 'base.html' %}

  {% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
  {% endblock %}

  {% block content %}
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th>Board</th>
          <th>Posts</th>
          <th>Topics</th>
          <th>Last Post</th>
        </tr>
      </thead>
      <tbody>
        {% for board in boards %}
          <tr>
            <td>
              <a href="{% url 'topics' board.pk %}">{{ board.name }}</a>
              <small class="text-muted d-block">{{ board.description }}</small>
            </td>
            <td class="align-middle">0</td>
            <td class="align-middle">0</td>
            <td></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endblock %}

mBoard/posts/templates/new_topic.html
{% extends 'base.html' %}

  {% block title %}Start a New Topic{% endblock %}

  {% block breadcrumb %}


    <li class="breadcrumb-item"><a href="{% url 'boards' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'topics' pk %}">{{ board }}</a></li>
    <li class="breadcrumb-item active">New Topic</li>
  {% endblock %}

  {% block content %}

    <form method="post">
      {% csrf_token %}
        <div class="form-group">
          <label for="id_subject">Subject</label>
          <input type="text" class="form-control" id="id_subject" name="subject">
        </div>
        <div class="form-group">
          <label for="id_message">Message</label>
          <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
          <div>

      <!--{{ form.as_p }}-->
      <button type="submit" class="btn btn-success">Post</button>
    </form>
  {% endblock %}

mBoard/posts/templates/topics.html
{% extends 'base.html' %}

{% block title %}
  {{ board.name }} - {{ block.super }}
{% endblock %}


{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards' %}">Boards</a></li>
  <li class="breadcrumb-item active">{{ boards.name }}</li>
{% endblock %}

{% block content %}
  <div class="mb-4">
    <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New Topic</a>
  </div>

  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in board.topics.all %}
        <tr>
          <td>{{ topic.subject }}</td>
          <td>{{ topic.starter.username }}</td>
          <td>0</td>
          <td>0</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}


<!--
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ board.name }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    <div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item"><a href="{% url 'boards' %}">Boards</a></li>
        <li class="breadcrumb-item active">{{ board.name }}</li>
      </ol>
    </div>
  </body>
</head>
-->

mBoard/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Boards</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    <div class="container">
      <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active">Boards</li>
      </ol>
      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
          </tr>
        </thead>
        <tbody>
          {% for board in boards %}
            <tr>
              <td>
                {{ board.name }}
                <small class="text-muted d-block">{{ board.description }}</small>
              </td>
              <td class="align-middle">0</td>
              <td class="align-middle">0</td>
              <td></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </body>
</html>